name: "Build ed-nezha-container"

on:
  workflow_dispatch:
  
jobs:
  Building:
    runs-on: ubuntu-latest
    name: "Build and push Argo-X images"
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Login to DockerHub
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push images
      run: |
        docker buildx build --push --platform linux/amd64 --tag ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }} .
